# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x03llm\",\n\nLLMRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0e\n\x06memory\x18\x02 \x03(\t\"!\n\x0bLLMResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t2A\n\nLLMService\x12\x33\n\x0eGenerateAnswer\x12\x0f.llm.LLMRequest\x1a\x10.llm.LLMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST']._serialized_start=26
  _globals['_LLMREQUEST']._serialized_end=70
  _globals['_LLMRESPONSE']._serialized_start=72
  _globals['_LLMRESPONSE']._serialized_end=105
  _globals['_LLMSERVICE']._serialized_start=107
  _globals['_LLMSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
